version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
    - mongodata:/data/db

  army-backend:
    build:
      context: .
    ports:
    - 7890:7890
    volumes:
    - ./.env:/app/.env
    depends_on:
    - mongo

volumes:
  mongodata:
